version: '3.8'

services:
  altwallet-agent-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: ${VERSION:-0.1.0}
    image: altwallet/checkout-agent:${VERSION:-0.1.0}
    container_name: altwallet-agent-api
    ports:
      - "8080:8080"
    environment:
      - PYTHONPATH=/app/src
    volumes:
      - ./data:/data:ro
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "org.opencontainers.image.version=${VERSION:-0.1.0}"
      - "org.opencontainers.image.title=AltWallet Checkout Agent"
      - "org.opencontainers.image.description=Core Engine MVP for checkout processing and scoring"
      - "org.opencontainers.image.vendor=AltWallet"
