# Example Docker Compose configuration for sidecar deployment
# This example shows how to deploy AltWallet Checkout Agent as a sidecar service

version: '3.8'

services:
  # AltWallet Checkout Agent sidecar
  altwallet-checkout-agent:
    image: altwallet/checkout-agent:latest
    container_name: altwallet-checkout-agent
    restart: unless-stopped
    
    # Environment variables
    environment:
      - DEPLOYMENT_MODE=sidecar
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - MAX_WORKERS=4
      - REQUEST_TIMEOUT=30
      - METRICS_ENABLED=true
      - TRACING_ENABLED=true
      - HEALTH_CHECK_ENABLED=true
      - HEALTH_CHECK_INTERVAL=30
      - CORS_ORIGINS=["*"]
      - API_KEY_REQUIRED=false
    
    # Port mapping
    ports:
      - "8000:8000"
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Volume mounts
    volumes:
      - ./config:/app/config:ro
      - ./logs:/app/logs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    
    # Network
    networks:
      - altwallet-network
    
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Security
    security_opt:
      - no-new-privileges:true
    user: "1000:1000"

  # Example merchant application (placeholder)
  merchant-app:
    image: nginx:alpine
    container_name: merchant-app
    restart: unless-stopped
    
    ports:
      - "8080:80"
    
    volumes:
      - ./merchant-app:/usr/share/nginx/html:ro
    
    networks:
      - altwallet-network
    
    depends_on:
      - altwallet-checkout-agent

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: altwallet-redis
    restart: unless-stopped
    
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    
    volumes:
      - redis-data:/data
    
    networks:
      - altwallet-network
    
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Prometheus for metrics (optional)
  prometheus:
    image: prom/prometheus:latest
    container_name: altwallet-prometheus
    restart: unless-stopped
    
    ports:
      - "9090:9090"
    
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    
    networks:
      - altwallet-network
    
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'

  # Grafana for visualization (optional)
  grafana:
    image: grafana/grafana:latest
    container_name: altwallet-grafana
    restart: unless-stopped
    
    ports:
      - "3000:3000"
    
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources:ro
    
    networks:
      - altwallet-network
    
    depends_on:
      - prometheus

networks:
  altwallet-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  redis-data:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
