# Approval Odds Configuration
# Two-stage approval-odds module configuration

# Stage 1: Rules Layer - Feature Weights (raw log-odds contributions)
rules_layer:
  # MCC-based weights (Merchant Category Code)
  mcc_weights:
    # High-risk MCCs (gambling, adult content, etc.)
    "7995": -2.5  # Gambling
    "7841": -2.0  # Video tape rental stores
    "7922": -1.8  # Theatrical producers
    # Medium-risk MCCs
    "5541": -0.5  # Gas stations
    "5542": -0.5  # Automated fuel dispensers
    # Low-risk MCCs
    "5411": 0.2   # Grocery stores
    "5311": 0.1   # Department stores
    "default": 0.0  # Default weight for unknown MCCs

  # Amount-based weights (log-scale)
  amount_weights:
    # Small amounts (likely legitimate)
    "0-10": 0.3
    "10-50": 0.1
    "50-100": 0.0
    "100-500": -0.2
    "500-1000": -0.5
    "1000-5000": -1.0
    "5000+": -2.0

  # Issuer family weights
  issuer_family_weights:
    "visa": 0.0
    "mastercard": 0.0
    "amex": -0.3
    "discover": -0.2
    "unknown": -0.5

  # Cross-border flag weight
  cross_border_weight: -1.5

  # Device/geo mismatch distance weights
  location_mismatch_weights:
    "0-10": 0.0    # Same city/region
    "10-50": -0.5  # Same state/province
    "50-200": -1.0 # Same country
    "200+": -2.0   # Different country

  # Velocity weights (24h and 7d)
  velocity_weights:
    "24h":
      "0-5": 0.1
      "5-10": -0.2
      "10-20": -0.5
      "20-50": -1.0
      "50+": -2.0
    "7d":
      "0-20": 0.0
      "20-50": -0.3
      "50-100": -0.8
      "100-200": -1.5
      "200+": -2.5

  # Chargeback history weights
  chargeback_weights:
    "0": 0.0
    "1": -0.5
    "2": -1.0
    "3+": -2.0

  # Merchant risk tier weights
  merchant_risk_weights:
    "low": 0.2
    "medium": 0.0
    "high": -1.0
    "unknown": -0.5

  # Loyalty tier weights
  loyalty_weights:
    "NONE": 0.0
    "SILVER": 0.3
    "GOLD": 0.6
    "PLATINUM": 1.0

  # Base score (intercept)
  base_score: 0.0

# Stage 2: Calibration Layer
calibration_layer:
  # Default calibration method
  method: "logistic"
  
  # Logistic (Platt) calibration parameters
  logistic:
    bias: 0.0      # Intercept term
    scale: 1.0     # Scaling factor
    
  # Isotonic calibration (for future use)
  isotonic:
    # Parameters would be learned from training data
    pass

# Output constraints
output:
  # Clamp approval probability to [min_prob, max_prob]
  min_probability: 0.01
  max_probability: 0.99
  
  # Random seed for deterministic behavior
  random_seed: 42
